// Code generated by Slice Machine. DO NOT EDIT.
import type * as prismic from "@prismicio/client"

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		| prismic.AnyRegularField
		| prismic.GroupField
		| prismic.NestedGroupField
		| prismic.SliceZone
	>,
	TLang extends string,
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
			TSubRelationship["customtypes"],
			TLang
		>
	} & { // Group
		[TGroup in Extract<
			TRelationship["fields"][number],
			| prismic.CustomTypeModelFetchGroupLevel1
			| prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
			infer TGroupData
		>
			? prismic.GroupField<
					PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
				>
			: never
	} & { // Other fields
		[TFieldKey in Extract<
			TRelationship["fields"][number],
			string
		>]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
	}

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string,
> = {
	[ID in Exclude<
		TCustomType[number],
		string
	>["id"]]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
			TLang
		>
	>
}[Exclude<TCustomType[number], string>["id"]]

/** Content for Kitchen Sink documents */
interface KitchenSinkDocumentData {
	/**
	 * Title field in _Kitchen Sink_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: kitchen_sink.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField

	/**
	 * Body field in _Kitchen Sink_
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: _None_
	 * - **API ID Path**: kitchen_sink.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField

	/**
	 * image field in _Kitchen Sink_
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: _None_
	 * - **API ID Path**: kitchen_sink.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * link field in _Kitchen Sink_
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: _None_
	 * - **API ID Path**: kitchen_sink.link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

	/**
	 * relationship field in _Kitchen Sink_
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: _None_
	 * - **API ID Path**: kitchen_sink.relationship
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	relationship: prismic.ContentRelationshipField
}

/**
 * Kitchen Sink document from Prismic
 *
 * - **API ID**: `kitchen_sink`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KitchenSinkDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<KitchenSinkDocumentData>,
		"kitchen_sink",
		Lang
	>

export type AllDocumentTypes = KitchenSinkDocument

declare module "@prismicio/client" {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig,
		): prismic.WriteClient<AllDocumentTypes>
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>
	}

	namespace Content {
		export type {
			KitchenSinkDocument,
			KitchenSinkDocumentData,
			AllDocumentTypes,
		}
	}
}
